In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)

In [3]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [6]:
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={ 'criterion' :['squared_error','absolute_error','friedman_mse'],
             'max_features' : [None,'sqrt','log2'],
             'n_estimators' : [100]}

grid = GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [100]},
             verbose=3)

In [9]:
# grid will handle r_score grid values and training and test data split internally.
#Hence seperate x_train, x_Test, ,y_train, y _test not required
re=grid.cv_results_
print( " The R score value for the best params {}:" .format(grid.best_params_))

 The R score value for the best params {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}:

In [10]:
# Evaluation will be handled by gridsearch in Cross validation
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.995559,0.141947,0.034262,0.003506,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.848910,0.770492,0.852791,0.818134,0.834473,0.824960,0.029840,8
1,0.766953,0.102515,0.038155,0.007992,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.856293,0.782051,0.858930,0.826684,0.843185,0.833428,0.028119,1
2,0.835619,0.064645,0.041513,0.006425,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.859070,0.777043,0.859557,0.824689,0.839028,0.831877,0.030382,4
3,4.218885,0.078497,0.027937,0.002143,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.837883,0.772646,0.847360,0.820496,0.836588,0.822994,0.026613,9
4,2.381948,0.044674,0.028610,0.002280,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.859252,0.773182,0.854864,0.827168,0.841210,0.831135,0.031079,5
5,2.527395,0.112070,0.028983,0.002840,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857404,0.780966,0.859244,0.828642,0.840635,0.833378,0.028525,2
6,0.934639,0.050359,0.030382,0.004367,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.847585,0.777055,0.859206,0.817021,0.834315,0.827036,0.028665,7
7,0.709490,0.050051,0.029166,0.002120,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856262,0.777684,0.859543,0.828395,0.838077,0.831992,0.029487,3
8,0.563654,0.073475,0.018780,0.005637,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858213,0.772366,0.858824,0.823929,0.838533,0.830373,0.031804,6

In [11]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI : "))
children_input=int(input("Children:"))
sex_male_input=int(input("Sex Male 0 or1 :"))
smoker_yes_input=int(input("Smoker yes 0 or 1:"))

Age: 34
BMI :  34
Children: 3
Sex Male 0 or1 : 1
Smoker yes 0 or 1: 1

In [12]:
future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future prediction {}" .format(future_prediction))

Future prediction [38453.1148807]

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(