In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [4]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [5]:
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [6]:
#from sklearn.preprocessing import StandardScaler   #section is added to check if r_score can be improved by doing STANDARDISATION
#sc=StandardScaler()
#x_train_scaled=sc.fit_transform(x_train)
#x_test_scaled=sc.transform(x_test)
#x_test_scaled

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={ "kernel" : ['rbf','poly','sigmoid'],
             "gamma" :['scale'],
              "C" : [10,100,1000]
           }
grid= GridSearchCV(SVR(), param_grid, refit=True, verbose=3 , n_jobs=-1 )
grid.fit(independent,dependent)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000], 'gamma': ['scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             verbose=3)

In [11]:
re=grid.cv_results_

print("The R score for the best params {} : " .format(grid.best_params_))

The R score for the best params {'C': 1000, 'gamma': 'scale', 'kernel': 'poly'} :

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.237118,0.007639,0.099317,0.003897,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,2
1,0.201863,0.022350,0.036512,0.002916,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",-0.125153,-0.081505,-0.111907,-0.131602,-0.179328,-0.125899,0.031794,4
2,0.266588,0.013326,0.054946,0.004924,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,3
3,0.259837,0.022543,0.118301,0.011894,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,8
4,0.243328,0.019362,0.040236,0.008298,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",-0.132885,-0.082461,-0.129220,-0.139962,-0.189219,-0.134749,0.033948,5
5,0.301984,0.037243,0.054288,0.003398,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,6
6,0.265149,0.035736,0.120484,0.011113,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,7
7,0.286031,0.011827,0.030997,0.002735,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",-0.080527,-0.028469,-0.073376,-0.086611,-0.134493,-0.080695,0.033795,1
8,0.224508,0.023843,0.034255,0.004891,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,9

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI : "))
children_input=int(input("Children:"))
sex_male_input=int(input("Sex Male 0 or1 :"))
smoker_yes_input=int(input("Smoker yes 0 or 1:"))

In [ ]:
future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future prediction {}:" .format(future_prediction))